"""change_media_type_to_string

Revision ID: 4b7c87a4a5c5
Revises: 6fc19ac5b52a
Create Date: 2026-09-01 20:27:49.342938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7c87a4a5c5'
down_revision: Union[str, Sequence[str], None] = '6fc19ac5b52a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
