"""add poster_url to categories

Revision ID: 4b87d74d46d7
Revises: e91853749a0c
Create Date: 2026-09-07 12:21:22.235970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b87d74d46d7'
down_revision: Union[str, Sequence[str], None] = 'e91853749a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('poster_url', sa.String(length=500), nullable=True))
    op.add_column('episodes', sa.Column('poster_url', sa.String(length=500), nullable=True))
    op.add_column('seasons', sa.Column('poster_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'poster_url')
    op.drop_column('episodes', 'poster_url')
    op.drop_column('categories', 'poster_url')
    # ### end Alembic commands ###
