"""change_media_type_to_string

Revision ID: ed2148d48384
Revises: 4b7c87a4a5c5
Create Date: 2026-09-01 20:30:15.710085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed2148d48384'
down_revision: Union[str, Sequence[str], None] = '4b7c87a4a5c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'type',
               existing_type=postgresql.ENUM('MOVIE', 'TV_SHOW', name='mediatype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('MOVIE', 'TV_SHOW', name='mediatype'),
               existing_nullable=False)
    # ### end Alembic commands ###
